zookeeper:
  # 每次重试时间间隔，单位毫秒
  baseSleepTimeMs: 1000
  # 重试次数
  maxRetries: 3
  # ookeeper服务连接id与端口
  connectString: 192.168.1.71:2181
  # 会话超时时间，单位毫秒
  sessionTimeoutMs: 5000
  # 连接创建超时时间，单位毫秒
  connection-timeout-ms: 5000